services:
  java_game:
    container_name: postgres-spring-boot-java_game
    image: postgres:18
    environment:
      #password is a must
      POSTGRES_PASSWORD: {password}
    volumes:
      # required created initial db and user
      - "./database/mount:/docker-entrypoint-initdb.d"
      - data:/var/lit/postgresql/data
    ports:
      # first port can be anything second one must be 5432
      - "15433:5432"

volumes:
  data:

